name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run ESLint
        run: yarn lint


      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build for GH Pages
        run: yarn build
        env:
          CI: false
          PUBLIC_URL: "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      # - name: Run FOSSA for license check
      #   run: fossa analyze
      #   env:
      #     FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

      # - name: Run Snyk for vulnerability check
      #   run: npx snyk test
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
